# Transifex configuration
project: greek-locale
username: dimitrys_af
source_language: en
target_languages:
  - el
filters:
  - filter_type: file
    include: '.*\.pot$'
source_files:
  - path: messages/*
    format: pot
