# Transifex configuration
# Transifex configuration
project: 'greek-locale'
hostname: 'https://www.transifex.com'
username: 'dimitrys_af'
source_language: 'en'
target_languages:
  - 'el'
filters:
  - filter_type: 'file'
    file_format: 'pot'
    source_language: 'en'
    translation_files_expression: 'messages/*/*<lang>.po'
    source_file: 'messages/*'
